var annotated_dup =
[
    [ "std", null, [
      [ "formatter&lt; tr::angle, CharT &gt;", "classstd_1_1formatter_3_01tr_1_1angle_00_01CharT_01_4.html", "classstd_1_1formatter_3_01tr_1_1angle_00_01CharT_01_4" ],
      [ "formatter&lt; tr::basic_inplace_string&lt; CharT, Capacity, Traits &gt;, CharT &gt;", "structstd_1_1formatter_3_01tr_1_1basic__inplace__string_3_01CharT_00_01Capacity_00_01Traits_01_4_00_01CharT_01_4.html", null ],
      [ "formatter&lt; tr::basic_zstring_view&lt; CharT, Traits &gt; &gt;", "structstd_1_1formatter_3_01tr_1_1basic__zstring__view_3_01CharT_00_01Traits_01_4_01_4.html", null ],
      [ "formatter&lt; tr::log_level &gt;", "classstd_1_1formatter_3_01tr_1_1log__level_01_4.html", "classstd_1_1formatter_3_01tr_1_1log__level_01_4" ],
      [ "formatter&lt; tr::log_message &gt;", "classstd_1_1formatter_3_01tr_1_1log__message_01_4.html", "classstd_1_1formatter_3_01tr_1_1log__message_01_4" ]
    ] ],
    [ "tr", "namespacetr.html", [
      [ "utf8", "namespacetr_1_1utf8.html", [
        [ "iterator", "classtr_1_1utf8_1_1iterator.html", "classtr_1_1utf8_1_1iterator" ],
        [ "indexed_iterator", "classtr_1_1utf8_1_1indexed__iterator.html", "classtr_1_1utf8_1_1indexed__iterator" ]
      ] ],
      [ "angle", "classtr_1_1angle.html", "classtr_1_1angle" ],
      [ "application", "classtr_1_1application.html", "classtr_1_1application" ],
      [ "atlas_entries", "classtr_1_1atlas__entries.html", "classtr_1_1atlas__entries" ],
      [ "atlas_packer", "classtr_1_1atlas__packer.html", "classtr_1_1atlas__packer" ],
      [ "audio_buffer", "classtr_1_1audio__buffer.html", "classtr_1_1audio__buffer" ],
      [ "audio_context", "classtr_1_1audio__context.html", "classtr_1_1audio__context" ],
      [ "audio_context_init_error", "classtr_1_1audio__context__init__error.html", "classtr_1_1audio__context__init__error" ],
      [ "audio_device", "classtr_1_1audio__device.html", "classtr_1_1audio__device" ],
      [ "audio_device_list_view_end_sentinel", "classtr_1_1audio__device__list__view__end__sentinel.html", null ],
      [ "audio_device_list_view_iterator", "classtr_1_1audio__device__list__view__iterator.html", "classtr_1_1audio__device__list__view__iterator" ],
      [ "audio_device_open_error", "structtr_1_1audio__device__open__error.html", "structtr_1_1audio__device__open__error" ],
      [ "audio_file_open_error", "classtr_1_1audio__file__open__error.html", "classtr_1_1audio__file__open__error" ],
      [ "audio_source", "classtr_1_1audio__source.html", "classtr_1_1audio__source" ],
      [ "audio_stream", "classtr_1_1audio__stream.html", "classtr_1_1audio__stream" ],
      [ "backbuffer_resize_event", "structtr_1_1backbuffer__resize__event.html", "structtr_1_1backbuffer__resize__event" ],
      [ "basic_dyn_vertex_buffer", "classtr_1_1basic__dyn__vertex__buffer.html", "classtr_1_1basic__dyn__vertex__buffer" ],
      [ "basic_graphics_buffer_map", "classtr_1_1basic__graphics__buffer__map.html", "classtr_1_1basic__graphics__buffer__map" ],
      [ "basic_inplace_string", "classtr_1_1basic__inplace__string.html", "classtr_1_1basic__inplace__string" ],
      [ "basic_shader_buffer", "classtr_1_1basic__shader__buffer.html", "classtr_1_1basic__shader__buffer" ],
      [ "basic_static_vertex_buffer", "classtr_1_1basic__static__vertex__buffer.html", "classtr_1_1basic__static__vertex__buffer" ],
      [ "basic_uniform_buffer", "classtr_1_1basic__uniform__buffer.html", "classtr_1_1basic__uniform__buffer" ],
      [ "basic_zstring_view", "classtr_1_1basic__zstring__view.html", "classtr_1_1basic__zstring__view" ],
      [ "benchmark", "classtr_1_1benchmark.html", "classtr_1_1benchmark" ],
      [ "binary_reader", "structtr_1_1binary__reader.html", null ],
      [ "binary_reader&lt; boost::unordered_flat_map&lt; Key, Value, Other... &gt; &gt;", "structtr_1_1binary__reader_3_01boost_1_1unordered__flat__map_3_01Key_00_01Value_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_reader&lt; boost::unordered_flat_set&lt; Key, Other... &gt; &gt;", "structtr_1_1binary__reader_3_01boost_1_1unordered__flat__set_3_01Key_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_reader&lt; boost::unordered_node_map&lt; Key, Value, Other... &gt; &gt;", "structtr_1_1binary__reader_3_01boost_1_1unordered__node__map_3_01Key_00_01Value_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_reader&lt; boost::unordered_node_set&lt; Key, Other... &gt; &gt;", "structtr_1_1binary__reader_3_01boost_1_1unordered__node__set_3_01Key_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_reader&lt; Defaulted &gt;", "structtr_1_1binary__reader_3_01Defaulted_01_4.html", "structtr_1_1binary__reader_3_01Defaulted_01_4" ],
      [ "binary_reader&lt; std::array&lt; Element, Size &gt; &gt;", "structtr_1_1binary__reader_3_01std_1_1array_3_01Element_00_01Size_01_4_01_4.html", null ],
      [ "binary_reader&lt; std::map&lt; Key, Value, Other... &gt; &gt;", "structtr_1_1binary__reader_3_01std_1_1map_3_01Key_00_01Value_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_reader&lt; std::pair&lt; First, Second &gt; &gt;", "structtr_1_1binary__reader_3_01std_1_1pair_3_01First_00_01Second_01_4_01_4.html", null ],
      [ "binary_reader&lt; std::set&lt; Key, Other... &gt; &gt;", "structtr_1_1binary__reader_3_01std_1_1set_3_01Key_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_reader&lt; std::string &gt;", "structtr_1_1binary__reader_3_01std_1_1string_01_4.html", null ],
      [ "binary_reader&lt; std::vector&lt; Element &gt; &gt;", "structtr_1_1binary__reader_3_01std_1_1vector_3_01Element_01_4_01_4.html", null ],
      [ "binary_reader&lt; tr::basic_inplace_string&lt; CharT, Capacity, Traits &gt; &gt;", "structtr_1_1binary__reader_3_01tr_1_1basic__inplace__string_3_01CharT_00_01Capacity_00_01Traits_01_4_01_4.html", "structtr_1_1binary__reader_3_01tr_1_1basic__inplace__string_3_01CharT_00_01Capacity_00_01Traits_01_4_01_4" ],
      [ "binary_reader&lt; tr::static_vector&lt; Element, Capacity &gt; &gt;", "structtr_1_1binary__reader_3_01tr_1_1static__vector_3_01Element_00_01Capacity_01_4_01_4.html", "structtr_1_1binary__reader_3_01tr_1_1static__vector_3_01Element_00_01Capacity_01_4_01_4" ],
      [ "binary_writer", "structtr_1_1binary__writer.html", null ],
      [ "binary_writer&lt; boost::unordered_flat_map&lt; Key, Value, Other... &gt; &gt;", "structtr_1_1binary__writer_3_01boost_1_1unordered__flat__map_3_01Key_00_01Value_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_writer&lt; boost::unordered_flat_set&lt; Key, Other... &gt; &gt;", "structtr_1_1binary__writer_3_01boost_1_1unordered__flat__set_3_01Key_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_writer&lt; boost::unordered_node_map&lt; Key, Value, Other... &gt; &gt;", "structtr_1_1binary__writer_3_01boost_1_1unordered__node__map_3_01Key_00_01Value_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_writer&lt; boost::unordered_node_set&lt; Key, Other... &gt; &gt;", "structtr_1_1binary__writer_3_01boost_1_1unordered__node__set_3_01Key_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_writer&lt; char[Size]&gt;", "structtr_1_1binary__writer_3_01char_0fSize_0e_4.html", null ],
      [ "binary_writer&lt; const char * &gt;", "structtr_1_1binary__writer_3_01const_01char_01_5_01_4.html", null ],
      [ "binary_writer&lt; Defaulted &gt;", "structtr_1_1binary__writer_3_01Defaulted_01_4.html", "structtr_1_1binary__writer_3_01Defaulted_01_4" ],
      [ "binary_writer&lt; Element[Size]&gt;", "structtr_1_1binary__writer_3_01Element_0fSize_0e_4.html", null ],
      [ "binary_writer&lt; std::array&lt; Element, Size &gt; &gt;", "structtr_1_1binary__writer_3_01std_1_1array_3_01Element_00_01Size_01_4_01_4.html", null ],
      [ "binary_writer&lt; std::map&lt; Key, Value, Other... &gt; &gt;", "structtr_1_1binary__writer_3_01std_1_1map_3_01Key_00_01Value_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_writer&lt; std::pair&lt; First, Second &gt; &gt;", "structtr_1_1binary__writer_3_01std_1_1pair_3_01First_00_01Second_01_4_01_4.html", null ],
      [ "binary_writer&lt; std::set&lt; Key, Other... &gt; &gt;", "structtr_1_1binary__writer_3_01std_1_1set_3_01Key_00_01Other_8_8_8_01_4_01_4.html", null ],
      [ "binary_writer&lt; std::span&lt; Element, Size &gt; &gt;", "structtr_1_1binary__writer_3_01std_1_1span_3_01Element_00_01Size_01_4_01_4.html", null ],
      [ "binary_writer&lt; std::string &gt;", "structtr_1_1binary__writer_3_01std_1_1string_01_4.html", null ],
      [ "binary_writer&lt; std::string_view &gt;", "structtr_1_1binary__writer_3_01std_1_1string__view_01_4.html", null ],
      [ "binary_writer&lt; std::vector&lt; Element &gt; &gt;", "structtr_1_1binary__writer_3_01std_1_1vector_3_01Element_01_4_01_4.html", null ],
      [ "binary_writer&lt; tr::basic_inplace_string&lt; CharT, Capacity, Traits &gt; &gt;", "structtr_1_1binary__writer_3_01tr_1_1basic__inplace__string_3_01CharT_00_01Capacity_00_01Traits_01_4_01_4.html", "structtr_1_1binary__writer_3_01tr_1_1basic__inplace__string_3_01CharT_00_01Capacity_00_01Traits_01_4_01_4" ],
      [ "binary_writer&lt; tr::basic_zstring_view&lt; CharT, Traits &gt; &gt;", "structtr_1_1binary__writer_3_01tr_1_1basic__zstring__view_3_01CharT_00_01Traits_01_4_01_4.html", null ],
      [ "binary_writer&lt; tr::static_vector&lt; Element, Capacity &gt; &gt;", "structtr_1_1binary__writer_3_01tr_1_1static__vector_3_01Element_00_01Capacity_01_4_01_4.html", "structtr_1_1binary__writer_3_01tr_1_1static__vector_3_01Element_00_01Capacity_01_4_01_4" ],
      [ "bitmap", "classtr_1_1bitmap.html", "classtr_1_1bitmap" ],
      [ "bitmap_atlas", "structtr_1_1bitmap__atlas.html", "structtr_1_1bitmap__atlas" ],
      [ "bitmap_load_error", "classtr_1_1bitmap__load__error.html", "classtr_1_1bitmap__load__error" ],
      [ "bitmap_save_error", "classtr_1_1bitmap__save__error.html", "classtr_1_1bitmap__save__error" ],
      [ "bitmap_view", "classtr_1_1bitmap__view.html", "classtr_1_1bitmap__view" ],
      [ "blend_mode", "structtr_1_1blend__mode.html", "structtr_1_1blend__mode" ],
      [ "circle", "structtr_1_1circle.html", "structtr_1_1circle" ],
      [ "cursor", "classtr_1_1cursor.html", "classtr_1_1cursor" ],
      [ "cursor_error", "classtr_1_1cursor__error.html", "classtr_1_1cursor__error" ],
      [ "custom_exception", "classtr_1_1custom__exception.html", "classtr_1_1custom__exception" ],
      [ "decryption_error", "classtr_1_1decryption__error.html", "classtr_1_1decryption__error" ],
      [ "defer", "classtr_1_1defer.html", "classtr_1_1defer" ],
      [ "dialog_filter", "structtr_1_1dialog__filter.html", "structtr_1_1dialog__filter" ],
      [ "directory_log_sink", "classtr_1_1directory__log__sink.html", "classtr_1_1directory__log__sink" ],
      [ "dyn_atlas", "classtr_1_1dyn__atlas.html", "classtr_1_1dyn__atlas" ],
      [ "dyn_index_buffer", "classtr_1_1dyn__index__buffer.html", "classtr_1_1dyn__index__buffer" ],
      [ "dyn_vertex_buffer", "classtr_1_1dyn__vertex__buffer.html", "classtr_1_1dyn__vertex__buffer" ],
      [ "enum_wrapper", "classtr_1_1enum__wrapper.html", "classtr_1_1enum__wrapper" ],
      [ "event", "classtr_1_1event.html", "classtr_1_1event" ],
      [ "exception", "classtr_1_1exception.html", "classtr_1_1exception" ],
      [ "file_not_found", "classtr_1_1file__not__found.html", "classtr_1_1file__not__found" ],
      [ "file_open_error", "classtr_1_1file__open__error.html", "classtr_1_1file__open__error" ],
      [ "fragment_shader", "classtr_1_1fragment__shader.html", "classtr_1_1fragment__shader" ],
      [ "framebuffer", "classtr_1_1framebuffer.html", "classtr_1_1framebuffer" ],
      [ "function_traits", "structtr_1_1function__traits.html", "structtr_1_1function__traits" ],
      [ "glyph_metrics", "structtr_1_1glyph__metrics.html", "structtr_1_1glyph__metrics" ],
      [ "graphics_benchmark", "classtr_1_1graphics__benchmark.html", "classtr_1_1graphics__benchmark" ],
      [ "graphics_buffer", "classtr_1_1graphics__buffer.html", "classtr_1_1graphics__buffer" ],
      [ "graphics_buffer_object_map", "classtr_1_1graphics__buffer__object__map.html", "classtr_1_1graphics__buffer__object__map" ],
      [ "graphics_buffer_span_map", "classtr_1_1graphics__buffer__span__map.html", "classtr_1_1graphics__buffer__span__map" ],
      [ "graphics_context", "classtr_1_1graphics__context.html", "classtr_1_1graphics__context" ],
      [ "graphics_context_init_error", "classtr_1_1graphics__context__init__error.html", "classtr_1_1graphics__context__init__error" ],
      [ "handle", "classtr_1_1handle.html", "classtr_1_1handle" ],
      [ "hsv", "structtr_1_1hsv.html", "structtr_1_1hsv" ],
      [ "imstream", "classtr_1_1imstream.html", "classtr_1_1imstream" ],
      [ "is_specialization_of", "structtr_1_1is__specialization__of.html", null ],
      [ "is_specialization_of_tv", "structtr_1_1is__specialization__of__tv.html", null ],
      [ "is_specialization_of_v", "structtr_1_1is__specialization__of__v.html", null ],
      [ "is_specialization_of_vt", "structtr_1_1is__specialization__of__vt.html", null ],
      [ "iterator_interface", "classtr_1_1iterator__interface.html", "classtr_1_1iterator__interface" ],
      [ "key_chord", "structtr_1_1key__chord.html", "structtr_1_1key__chord" ],
      [ "key_down_event", "structtr_1_1key__down__event.html", "structtr_1_1key__down__event" ],
      [ "key_up_event", "structtr_1_1key__up__event.html", "structtr_1_1key__up__event" ],
      [ "keyboard_state", "classtr_1_1keyboard__state.html", "classtr_1_1keyboard__state" ],
      [ "line_segment", "structtr_1_1line__segment.html", "structtr_1_1line__segment" ],
      [ "localization_map", "classtr_1_1localization__map.html", "classtr_1_1localization__map" ],
      [ "lock_free_queue", "classtr_1_1lock__free__queue.html", "classtr_1_1lock__free__queue" ],
      [ "log_message", "structtr_1_1log__message.html", "structtr_1_1log__message" ],
      [ "log_sink", "classtr_1_1log__sink.html", "classtr_1_1log__sink" ],
      [ "logger", "classtr_1_1logger.html", "classtr_1_1logger" ],
      [ "maybe_empty_t", "structtr_1_1maybe__empty__t.html", null ],
      [ "memorybuf", "classtr_1_1memorybuf.html", "classtr_1_1memorybuf" ],
      [ "mouse_down_event", "structtr_1_1mouse__down__event.html", "structtr_1_1mouse__down__event" ],
      [ "mouse_motion_event", "structtr_1_1mouse__motion__event.html", "structtr_1_1mouse__motion__event" ],
      [ "mouse_state", "structtr_1_1mouse__state.html", "structtr_1_1mouse__state" ],
      [ "mouse_up_event", "structtr_1_1mouse__up__event.html", "structtr_1_1mouse__up__event" ],
      [ "mouse_wheel_event", "structtr_1_1mouse__wheel__event.html", "structtr_1_1mouse__wheel__event" ],
      [ "mstream", "classtr_1_1mstream.html", "classtr_1_1mstream" ],
      [ "normalized", "structtr_1_1normalized.html", null ],
      [ "omstream", "classtr_1_1omstream.html", "classtr_1_1omstream" ],
      [ "opt_ref", "classtr_1_1opt__ref.html", "classtr_1_1opt__ref" ],
      [ "orientation", "structtr_1_1orientation.html", "structtr_1_1orientation" ],
      [ "out_handle_t", "classtr_1_1out__handle__t.html", "classtr_1_1out__handle__t" ],
      [ "out_of_memory", "structtr_1_1out__of__memory.html", "structtr_1_1out__of__memory" ],
      [ "owning_shader_pipeline", "classtr_1_1owning__shader__pipeline.html", "classtr_1_1owning__shader__pipeline" ],
      [ "path_error", "classtr_1_1path__error.html", "classtr_1_1path__error" ],
      [ "ping_pong_target", "classtr_1_1ping__pong__target.html", "classtr_1_1ping__pong__target" ],
      [ "pointer_iterator", "classtr_1_1pointer__iterator.html", "classtr_1_1pointer__iterator" ],
      [ "quit_event", "structtr_1_1quit__event.html", null ],
      [ "rectangle", "structtr_1_1rectangle.html", "structtr_1_1rectangle" ],
      [ "rectangle_edges", "structtr_1_1rectangle__edges.html", "structtr_1_1rectangle__edges" ],
      [ "ref", "classtr_1_1ref.html", "classtr_1_1ref" ],
      [ "render_target", "classtr_1_1render__target.html", "classtr_1_1render__target" ],
      [ "rgb8", "structtr_1_1rgb8.html", "structtr_1_1rgb8" ],
      [ "rgba8", "structtr_1_1rgba8.html", "structtr_1_1rgba8" ],
      [ "rgbaf", "structtr_1_1rgbaf.html", "structtr_1_1rgbaf" ],
      [ "rgbf", "structtr_1_1rgbf.html", "structtr_1_1rgbf" ],
      [ "rng", "classtr_1_1rng.html", "classtr_1_1rng" ],
      [ "scan_chord", "structtr_1_1scan__chord.html", "structtr_1_1scan__chord" ],
      [ "scan_state", "classtr_1_1scan__state.html", "classtr_1_1scan__state" ],
      [ "set_clipboard_error", "classtr_1_1set__clipboard__error.html", "classtr_1_1set__clipboard__error" ],
      [ "shader", "classtr_1_1shader.html", "classtr_1_1shader" ],
      [ "shader_array", "classtr_1_1shader__array.html", "classtr_1_1shader__array" ],
      [ "shader_buffer", "classtr_1_1shader__buffer.html", "classtr_1_1shader__buffer" ],
      [ "shader_load_error", "classtr_1_1shader__load__error.html", "classtr_1_1shader__load__error" ],
      [ "shader_pipeline", "classtr_1_1shader__pipeline.html", "classtr_1_1shader__pipeline" ],
      [ "size_type", "structtr_1_1size__type.html", "structtr_1_1size__type" ],
      [ "static_index_buffer", "classtr_1_1static__index__buffer.html", "classtr_1_1static__index__buffer" ],
      [ "static_vector", "classtr_1_1static__vector.html", "classtr_1_1static__vector" ],
      [ "static_vertex_buffer", "classtr_1_1static__vertex__buffer.html", "classtr_1_1static__vertex__buffer" ],
      [ "stdout_log_sink", "classtr_1_1stdout__log__sink.html", "classtr_1_1stdout__log__sink" ],
      [ "stopwatch", "classtr_1_1stopwatch.html", "classtr_1_1stopwatch" ],
      [ "string_eq", "structtr_1_1string__eq.html", "structtr_1_1string__eq" ],
      [ "string_hash", "structtr_1_1string__hash.html", "structtr_1_1string__hash" ],
      [ "string_literal", "structtr_1_1string__literal.html", "structtr_1_1string__literal" ],
      [ "sub_bitmap", "classtr_1_1sub__bitmap.html", "classtr_1_1sub__bitmap" ],
      [ "text_input_event", "structtr_1_1text__input__event.html", "structtr_1_1text__input__event" ],
      [ "texture", "classtr_1_1texture.html", "classtr_1_1texture" ],
      [ "texture_target", "classtr_1_1texture__target.html", "classtr_1_1texture__target" ],
      [ "texture_view", "classtr_1_1texture__view.html", "classtr_1_1texture__view" ],
      [ "timer", "classtr_1_1timer.html", "classtr_1_1timer" ],
      [ "triangle", "structtr_1_1triangle.html", "structtr_1_1triangle" ],
      [ "ttf_measure_result", "structtr_1_1ttf__measure__result.html", "structtr_1_1ttf__measure__result" ],
      [ "ttfont", "classtr_1_1ttfont.html", "classtr_1_1ttfont" ],
      [ "ttfont_error", "classtr_1_1ttfont__error.html", "classtr_1_1ttfont__error" ],
      [ "ttfont_load_error", "classtr_1_1ttfont__load__error.html", "classtr_1_1ttfont__load__error" ],
      [ "ttfont_render_error", "classtr_1_1ttfont__render__error.html", "classtr_1_1ttfont__render__error" ],
      [ "uniform_buffer", "classtr_1_1uniform__buffer.html", "classtr_1_1uniform__buffer" ],
      [ "unknown_event", "structtr_1_1unknown__event.html", null ],
      [ "vertex_attribute", "structtr_1_1vertex__attribute.html", "structtr_1_1vertex__attribute" ],
      [ "vertex_binding", "structtr_1_1vertex__binding.html", "structtr_1_1vertex__binding" ],
      [ "vertex_binding_tag", "structtr_1_1vertex__binding__tag.html", "structtr_1_1vertex__binding__tag" ],
      [ "vertex_format", "classtr_1_1vertex__format.html", "classtr_1_1vertex__format" ],
      [ "vertex_shader", "classtr_1_1vertex__shader.html", "classtr_1_1vertex__shader" ],
      [ "window", "classtr_1_1window.html", "classtr_1_1window" ],
      [ "window_error", "classtr_1_1window__error.html", "classtr_1_1window__error" ],
      [ "window_gain_focus_event", "structtr_1_1window__gain__focus__event.html", "structtr_1_1window__gain__focus__event" ],
      [ "window_hide_event", "structtr_1_1window__hide__event.html", "structtr_1_1window__hide__event" ],
      [ "window_lose_focus_event", "structtr_1_1window__lose__focus__event.html", "structtr_1_1window__lose__focus__event" ],
      [ "window_mouse_enter_event", "structtr_1_1window__mouse__enter__event.html", "structtr_1_1window__mouse__enter__event" ],
      [ "window_mouse_leave_event", "structtr_1_1window__mouse__leave__event.html", "structtr_1_1window__mouse__leave__event" ],
      [ "window_open_error", "classtr_1_1window__open__error.html", "classtr_1_1window__open__error" ],
      [ "window_parameters", "structtr_1_1window__parameters.html", "structtr_1_1window__parameters" ],
      [ "window_show_event", "structtr_1_1window__show__event.html", "structtr_1_1window__show__event" ],
      [ "window_view", "classtr_1_1window__view.html", "classtr_1_1window__view" ]
    ] ]
];