var concepts =
[
    [ "tr", "namespacetr.html", [
      [ "utf8", "namespacetr_1_1utf8.html", [
        [ "input_iterator", "concepttr_1_1utf8_1_1input__iterator.html", null ],
        [ "output_string", "concepttr_1_1utf8_1_1output__string.html", null ]
      ] ],
      [ "arithmetic", "concepttr_1_1arithmetic.html", null ],
      [ "atlas_entries_value_type", "concepttr_1_1atlas__entries__value__type.html", null ],
      [ "binary_constructible", "concepttr_1_1binary__constructible.html", null ],
      [ "binary_flushable_iterator", "concepttr_1_1binary__flushable__iterator.html", null ],
      [ "binary_readable", "concepttr_1_1binary__readable.html", null ],
      [ "binary_writable", "concepttr_1_1binary__writable.html", null ],
      [ "borrowed_mutable_standard_layout_range", "concepttr_1_1borrowed__mutable__standard__layout__range.html", null ],
      [ "borrowed_standard_layout_range", "concepttr_1_1borrowed__standard__layout__range.html", null ],
      [ "borrowed_typed_contiguous_const_range", "concepttr_1_1borrowed__typed__contiguous__const__range.html", null ],
      [ "borrowed_typed_contiguous_mutable_range", "concepttr_1_1borrowed__typed__contiguous__mutable__range.html", null ],
      [ "const_lvalue_reference", "concepttr_1_1const__lvalue__reference.html", null ],
      [ "const_qualified", "concepttr_1_1const__qualified.html", null ],
      [ "cv_unqualified", "concepttr_1_1cv__unqualified.html", null ],
      [ "cv_unqualified_object", "concepttr_1_1cv__unqualified__object.html", null ],
      [ "cvref_specialization_of", "concepttr_1_1cvref__specialization__of.html", null ],
      [ "cvref_specialization_of_tv", "concepttr_1_1cvref__specialization__of__tv.html", null ],
      [ "cvref_specialization_of_v", "concepttr_1_1cvref__specialization__of__v.html", null ],
      [ "cvref_specialization_of_vt", "concepttr_1_1cvref__specialization__of__vt.html", null ],
      [ "debug_writable_benchmark", "concepttr_1_1debug__writable__benchmark.html", null ],
      [ "default_constructible_handle_deleter", "concepttr_1_1default__constructible__handle__deleter.html", null ],
      [ "enumerator", "concepttr_1_1enumerator.html", null ],
      [ "equality_predicate", "concepttr_1_1equality__predicate.html", null ],
      [ "event_type", "concepttr_1_1event__type.html", null ],
      [ "event_visitor", "concepttr_1_1event__visitor.html", null ],
      [ "formattable", "concepttr_1_1formattable.html", null ],
      [ "formattable_with", "concepttr_1_1formattable__with.html", null ],
      [ "handle_deleter", "concepttr_1_1handle__deleter.html", null ],
      [ "hash_keylike", "concepttr_1_1hash__keylike.html", null ],
      [ "hasher", "concepttr_1_1hasher.html", null ],
      [ "index_range", "concepttr_1_1index__range.html", null ],
      [ "layered_renderer", "concepttr_1_1layered__renderer.html", null ],
      [ "layered_renderer_drawer", "concepttr_1_1layered__renderer__drawer.html", null ],
      [ "layered_renderer_or_drawer", "concepttr_1_1layered__renderer__or__drawer.html", null ],
      [ "lvalue_reference", "concepttr_1_1lvalue__reference.html", null ],
      [ "move_assignable", "concepttr_1_1move__assignable.html", null ],
      [ "non_const_lvalue_reference", "concepttr_1_1non__const__lvalue__reference.html", null ],
      [ "object", "concepttr_1_1object.html", null ],
      [ "one_of", "concepttr_1_1one__of.html", null ],
      [ "pointer", "concepttr_1_1pointer.html", null ],
      [ "reference", "concepttr_1_1reference.html", null ],
      [ "rvalue_reference", "concepttr_1_1rvalue__reference.html", null ],
      [ "sized_output_range", "concepttr_1_1sized__output__range.html", null ],
      [ "span_or_ref_to_binary_readable", "concepttr_1_1span__or__ref__to__binary__readable.html", null ],
      [ "specialization_of", "concepttr_1_1specialization__of.html", null ],
      [ "specialization_of_tv", "concepttr_1_1specialization__of__tv.html", null ],
      [ "specialization_of_v", "concepttr_1_1specialization__of__v.html", null ],
      [ "specialization_of_vt", "concepttr_1_1specialization__of__vt.html", null ],
      [ "standard_layout", "concepttr_1_1standard__layout.html", null ],
      [ "standard_layout_range", "concepttr_1_1standard__layout__range.html", null ],
      [ "typed_contiguous_const_range", "concepttr_1_1typed__contiguous__const__range.html", null ],
      [ "typed_contiguous_mutable_range", "concepttr_1_1typed__contiguous__mutable__range.html", null ],
      [ "typed_input_iterator", "concepttr_1_1typed__input__iterator.html", null ],
      [ "typed_input_range", "concepttr_1_1typed__input__range.html", null ],
      [ "valid_format_string_for", "concepttr_1_1valid__format__string__for.html", null ],
      [ "volatile_qualified", "concepttr_1_1volatile__qualified.html", null ]
    ] ]
];