var localization__script__error_8hpp =
[
    [ "tr::localization_script_unexpected_backslash", "structtr_1_1localization__script__unexpected__backslash.html", "structtr_1_1localization__script__unexpected__backslash" ],
    [ "tr::localization_script_unexpected_slash", "structtr_1_1localization__script__unexpected__slash.html", "structtr_1_1localization__script__unexpected__slash" ],
    [ "tr::localization_script_unknown_escape_sequence", "structtr_1_1localization__script__unknown__escape__sequence.html", "structtr_1_1localization__script__unknown__escape__sequence" ],
    [ "tr::localization_script_unterminated_multiline_comment", "structtr_1_1localization__script__unterminated__multiline__comment.html", "structtr_1_1localization__script__unterminated__multiline__comment" ],
    [ "tr::localization_script_unterminated_string", "structtr_1_1localization__script__unterminated__string.html", "structtr_1_1localization__script__unterminated__string" ],
    [ "tr::localization_script_expected_symbol", "structtr_1_1localization__script__expected__symbol.html", "structtr_1_1localization__script__expected__symbol" ],
    [ "tr::localization_script_expected_closing_brace", "structtr_1_1localization__script__expected__closing__brace.html", "structtr_1_1localization__script__expected__closing__brace" ],
    [ "tr::localization_script_extraneous_closing_brace", "structtr_1_1localization__script__extraneous__closing__brace.html", "structtr_1_1localization__script__extraneous__closing__brace" ],
    [ "tr::localization_script_expected_symbol_or_closing_brace", "structtr_1_1localization__script__expected__symbol__or__closing__brace.html", "structtr_1_1localization__script__expected__symbol__or__closing__brace" ],
    [ "tr::localization_script_expected_equals_or_opening_brace", "structtr_1_1localization__script__expected__equals__or__opening__brace.html", "structtr_1_1localization__script__expected__equals__or__opening__brace" ],
    [ "tr::localization_script_expected_string", "structtr_1_1localization__script__expected__string.html", "structtr_1_1localization__script__expected__string" ],
    [ "tr::localization_script_duplicate_key", "structtr_1_1localization__script__duplicate__key.html", "structtr_1_1localization__script__duplicate__key" ],
    [ "tr::localization_error_formatter&lt; Error, Base &gt;", "structtr_1_1localization__error__formatter.html", "structtr_1_1localization__error__formatter" ],
    [ "std::formatter&lt; tr::localization_token_type &gt;", "structstd_1_1formatter_3_01tr_1_1localization__token__type_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__token__type_01_4" ],
    [ "std::formatter&lt; tr::localization_script_unexpected_backslash &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__unexpected__backslash_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__unexpected__backslash_01_4" ],
    [ "std::formatter&lt; tr::localization_script_unexpected_slash &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__unexpected__slash_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__unexpected__slash_01_4" ],
    [ "std::formatter&lt; tr::localization_script_unknown_escape_sequence &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__unknown__escape__sequence_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__unknown__escape__sequence_01_4" ],
    [ "std::formatter&lt; tr::localization_script_unterminated_multiline_comment &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__unterminated__multiline__comment_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__unterminated__multiline__comment_01_4" ],
    [ "std::formatter&lt; tr::localization_script_unterminated_string &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__unterminated__string_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__unterminated__string_01_4" ],
    [ "std::formatter&lt; tr::localization_script_expected_symbol &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__expected__symbol_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__expected__symbol_01_4" ],
    [ "std::formatter&lt; tr::localization_script_expected_closing_brace &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__expected__closing__brace_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__expected__closing__brace_01_4" ],
    [ "std::formatter&lt; tr::localization_script_extraneous_closing_brace &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__extraneous__closing__brace_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__extraneous__closing__brace_01_4" ],
    [ "std::formatter&lt; tr::localization_script_expected_symbol_or_closing_brace &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__expected__symbol__or__closing__brace_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__expected__symbol__or__closing__brace_01_4" ],
    [ "std::formatter&lt; tr::localization_script_expected_equals_or_opening_brace &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__expected__equals__or__opening__brace_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__expected__equals__or__opening__brace_01_4" ],
    [ "std::formatter&lt; tr::localization_script_expected_string &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__expected__string_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__expected__string_01_4" ],
    [ "std::formatter&lt; tr::localization_script_duplicate_key &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__duplicate__key_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__duplicate__key_01_4" ],
    [ "std::formatter&lt; tr::localization_script_error &gt;", "structstd_1_1formatter_3_01tr_1_1localization__script__error_01_4.html", "structstd_1_1formatter_3_01tr_1_1localization__script__error_01_4" ],
    [ "tr::localization_script_error", "namespacetr.html#a5d0b9d07f28d7988881dea3b58bec727", null ],
    [ "tr::localization_token_type", "namespacetr.html#a358cbb7b209d738d608455b760766575", [
      [ "tr::localization_token_type::none", "namespacetr.html#a358cbb7b209d738d608455b760766575a334c4a4c42fdb79d7ebc3e73b517e6f8", null ],
      [ "tr::localization_token_type::symbol", "namespacetr.html#a358cbb7b209d738d608455b760766575a97bff26855a8bfa63e05d5477e794b24", null ],
      [ "tr::localization_token_type::string", "namespacetr.html#a358cbb7b209d738d608455b760766575ab45cffe084dd3d20d928bee85e7b0f21", null ],
      [ "tr::localization_token_type::equals", "namespacetr.html#a358cbb7b209d738d608455b760766575a51c3f59625962b899c03595d6cdfb284", null ],
      [ "tr::localization_token_type::opening_brace", "namespacetr.html#a358cbb7b209d738d608455b760766575a5b576df0219a82d4d7565bb829868522", null ],
      [ "tr::localization_token_type::closing_brace", "namespacetr.html#a358cbb7b209d738d608455b760766575a3906703432df907e74d660387706fcbb", null ]
    ] ]
];