/// @file
/// @brief Provides `tr::rng`.

#pragma once
#include <tr/utility/angle.hpp>
#include <tr/utility/macro.hpp>
#include <tr/utility/rectangle.hpp>

//

namespace tr
{
	/// Generates a random seed.
	/// @return Random 64-bit seed.
	[[nodiscard]] u64 generate_random_seed();

	/// Xorshiftr128+ random number generator.
	class rng
	{
	  public:
		/// @name Constructors
		/// @{

		/// Initializes RNG.
		/// @param seed Seed to initialize the generator with.
		[[nodiscard]] rng(u64 seed = generate_random_seed()) noexcept;

		/// @}
		/// @name Raw
		/// @{

		/// Advances the RNG and returns a value.
		/// @return New randomly-generated value.
		u64 advance() noexcept;

		/// @}
		/// @name Generation
		/// @{

		/// Generates a random integral value.
		/// @tparam Integer Integer type.
		/// @return Random integral value.
		template <std::integral Integer>
		[[nodiscard]] Integer generate() noexcept
		{
			// Upper bits of the value generated by advance() have better randomness.
			if constexpr (std::same_as<Integer, bool>) {
				return advance() >> 63;
			}
			else {
				return static_cast<Integer>(advance() >> ((sizeof(advance()) - sizeof(Integer)) * 4));
			}
		}

		/// Generates a random integral value in the range [0, `max`).
		/// @tparam Integer Integer type.
		/// @param max Upper bound of the random range.
		/// @pre `max` must be greater than 0.
		/// @return Random integral value constrained to [0, `max`).
		template <std::integral Integer>
		[[nodiscard]] Integer generate(Integer max) noexcept
		{
			TR_ASSERT(max > 0, "RNG range maximum must be greater than 0 (Currently: {}).", max);

			return static_cast<Integer>(generate<std::make_unsigned_t<Integer>>() % max);
		}

		/// Generates a random integral value in the range [`min`, `max`).
		/// @tparam Integer Integer type.
		/// @param min Lower bound of the random range.
		/// @param max Upper bound of the random range.
		/// @pre `min` must be less than `max`.
		/// @return Random integral value constrained to [`min`, `max`).
		template <std::integral Integer>
		[[nodiscard]] Integer generate(Integer min, Integer max) noexcept
		{
			TR_ASSERT(min < max, "RNG range minimum must be less than the maximum (Currenly: {} !< {})", min, max);

			return static_cast<Integer>(generate<std::make_unsigned_t<Integer>>() % (max - min) + min);
		}

		/// Generates a random floating point value in the range [0, 1).
		/// @tparam FloatingPoint Floating-point type.
		/// @return Random floating-point value constrained to [0, 1).
		template <std::floating_point FloatingPoint>
		[[nodiscard]] FloatingPoint generate() noexcept
		{
			return static_cast<FloatingPoint>(advance()) / static_cast<FloatingPoint>(UINT64_MAX);
		}

		/// Generates a random floating point value in the range [0, `max`).
		/// @tparam FloatingPoint Floating-point type.
		/// @param max Upper bound of the random range.
		/// @pre `max` must be greater than 0.
		/// @return Random floating-point value constrained to [0, `max`).
		template <std::floating_point FloatingPoint>
		[[nodiscard]] FloatingPoint generate(FloatingPoint max) noexcept
		{
			return generate<FloatingPoint>() * max;
		}

		/// Generates a random floating point value in the range [`min`, `max`).
		/// @tparam FloatingPoint Floating-point type.
		/// @param min Lower bound of the random range.
		/// @param max Upper bound of the random range.
		/// @pre `min` must be less than `max`.
		/// @return Random floating-point value constrained to [`min`, `max`).
		template <std::floating_point FloatingPoint>
		[[nodiscard]] FloatingPoint generate(FloatingPoint min, FloatingPoint max) noexcept
		{
			TR_ASSERT(min < max, "RNG range minimum must be less than the maximum (Currenly: {} !< {})", min, max);

			return generate<FloatingPoint>() * (max - min) + min;
		}

		/// Generates a random angle value in the range [0tr, 1tr).
		/// @return Random angle in the range [0tr, 1tr).
		template <std::same_as<angle>>
		[[nodiscard]] angle generate() noexcept
		{
			return turns(generate<float>());
		}

		/// Generates a random angle value in the range [0, `max`).
		/// @param max Upper bound of the random range.
		/// @pre `max` must be greater than 0.
		/// @return Random angle in the range [0, `max`).
		[[nodiscard]] angle generate(angle max) noexcept;

		/// Generates a random angle value in the range [`min`, `max`).
		/// @param min Lower bound of the random range.
		/// @param max Upper bound of the random range.
		/// @pre `min` must be less than `max`.
		/// @return Random angle in the range [`min`, `max`).
		[[nodiscard]] angle generate(angle min, angle max) noexcept;

		/// Generates a random vector with a specific magnitude.
		/// @param magnitude Magnitude of the vector.
		/// @return Vector with a set magnitude and random direction.
		template <std::same_as<glm::vec2>>
		[[nodiscard]] glm::vec2 generate(float magnitude) noexcept
		{
			// Prefer this over generating an angle because trigonometric functions don't produce uniform results across platforms.
			const float sin2{generate<float>()};
			const float sin{std::sqrt(sin2) * generate_sign()};
			const float cos{std::sqrt(1 - sin2) * generate_sign()};
			return {magnitude * cos, magnitude * sin};
		}

		/// Generates a random point within a rectangular region.
		/// @param region Region to constrain the vector to.
		/// @return Vector to a random point within `region`.
		template <std::same_as<glm::vec2>>
		[[nodiscard]] glm::vec2 generate(const tr::rectangle<float>& region) noexcept
		{
			return {generate(region.tl.x, region.tl.x + region.size.x), generate(region.tl.y, region.tl.y + region.size.y)};
		}

		/// Generates a random sign (-1 or 1).
		/// @return `-1` or `1`.
		[[nodiscard]] int generate_sign() noexcept;

		/// @}

	  private:
		/// Internal state of the generator.
		u64 m_state[2];
	};
} // namespace tr