var searchData=
[
  ['target_0',['&lt;span class=&quot;tt&quot;&gt;tr_target_template(TARGET)&lt;/span&gt;',['../md_pages_2cmake.html#autotoc_md16',1,'']]],
  ['target_20input_5ffile_20output_5ffile_20variable_5fname_1',['TARGET INPUT_FILE OUTPUT_FILE VARIABLE_NAME',['../md_pages_2cmake.html#autotoc_md14',1,'&lt;span class=&quot;tt&quot;&gt;tr_generate_embeddable_binary(TARGET, INPUT_FILE, OUTPUT_FILE, VARIABLE_NAME)&lt;/span&gt;'],['../md_pages_2cmake.html#autotoc_md13',1,'&lt;span class=&quot;tt&quot;&gt;tr_generate_embeddable_string(TARGET, INPUT_FILE, OUTPUT_FILE, VARIABLE_NAME)&lt;/span&gt;']]],
  ['tooling_2',['Tooling',['../md_pages_2building.html#autotoc_md1',1,'']]],
  ['tr_5fdo_5fnothing_3',['&lt;span class=&quot;tt&quot;&gt;TR_DO_NOTHING&lt;/span&gt;',['../md_pages_2cmake.html#autotoc_md11',1,'']]],
  ['tr_5fgenerate_5fembeddable_5fbinary_20target_20input_5ffile_20output_5ffile_20variable_5fname_4',['&lt;span class=&quot;tt&quot;&gt;tr_generate_embeddable_binary(TARGET, INPUT_FILE, OUTPUT_FILE, VARIABLE_NAME)&lt;/span&gt;',['../md_pages_2cmake.html#autotoc_md14',1,'']]],
  ['tr_5fgenerate_5fembeddable_5fstring_20target_20input_5ffile_20output_5ffile_20variable_5fname_5',['&lt;span class=&quot;tt&quot;&gt;tr_generate_embeddable_string(TARGET, INPUT_FILE, OUTPUT_FILE, VARIABLE_NAME)&lt;/span&gt;',['../md_pages_2cmake.html#autotoc_md13',1,'']]],
  ['tr_5fgit_5fhash_5fsetup_6',['&lt;span class=&quot;tt&quot;&gt;tr_git_hash_setup()&lt;/span&gt;',['../md_pages_2cmake.html#autotoc_md15',1,'']]],
  ['tr_5fhas_5fclang_20tr_5fhas_5fclang_5fcl_20tr_5fhas_5fmsvc_7',['&lt;span class=&quot;tt&quot;&gt;TR_HAS_GCC&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_CLANG&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_CLANG_CL&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_MSVC&lt;/span&gt;',['../md_pages_2cmake.html#autotoc_md10',1,'']]],
  ['tr_5fhas_5fclang_5fcl_20tr_5fhas_5fmsvc_8',['&lt;span class=&quot;tt&quot;&gt;TR_HAS_GCC&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_CLANG&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_CLANG_CL&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_MSVC&lt;/span&gt;',['../md_pages_2cmake.html#autotoc_md10',1,'']]],
  ['tr_5fhas_5fgcc_20tr_5fhas_5fclang_20tr_5fhas_5fclang_5fcl_20tr_5fhas_5fmsvc_9',['&lt;span class=&quot;tt&quot;&gt;TR_HAS_GCC&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_CLANG&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_CLANG_CL&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_MSVC&lt;/span&gt;',['../md_pages_2cmake.html#autotoc_md10',1,'']]],
  ['tr_5fhas_5fmsvc_10',['&lt;span class=&quot;tt&quot;&gt;TR_HAS_GCC&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_CLANG&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_CLANG_CL&lt;/span&gt;, &lt;span class=&quot;tt&quot;&gt;TR_HAS_MSVC&lt;/span&gt;',['../md_pages_2cmake.html#autotoc_md10',1,'']]],
  ['tr_5ftarget_5ftemplate_20target_11',['&lt;span class=&quot;tt&quot;&gt;tr_target_template(TARGET)&lt;/span&gt;',['../md_pages_2cmake.html#autotoc_md16',1,'']]]
];
