///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                       //
// Implements the templated parts of rng.hpp.                                                                                            //
//                                                                                                                                       //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once
#include "../macro.hpp"
#include "../rng.hpp"

/////////////////////////////////////////////////////////////////// RNG ///////////////////////////////////////////////////////////////////

template <std::integral Integer> Integer tr::rng::generate()
{
	// Upper bits of the value generated by advance() have better randomness.
	if constexpr (std::same_as<Integer, bool>) {
		return advance() >> 63;
	}
	else {
		return Integer(advance() >> ((sizeof(advance()) - sizeof(Integer)) * 4));
	}
}

template <std::integral Integer> Integer tr::rng::generate(Integer max)
{
	TR_ASSERT(max > 0, "RNG range maximum must be greater than 0 (Currently: {}).", max);

	return Integer(generate<std::make_unsigned_t<Integer>>() % max);
}

template <std::integral Integer> Integer tr::rng::generate(Integer min, Integer max)
{
	TR_ASSERT(min < max, "RNG range minimum must be less than the maximum (Currenly: {} !< {})", min, max);

	return Integer(generate<std::make_unsigned_t<Integer>>() % (max - min) + min);
}

template <std::floating_point FloatingPoint> FloatingPoint tr::rng::generate()
{
	return FloatingPoint(advance()) / FloatingPoint(UINT64_MAX);
}

template <std::floating_point FloatingPoint> FloatingPoint tr::rng::generate(FloatingPoint max)
{
	return generate<FloatingPoint>() * max;
}

template <std::floating_point FloatingPoint> FloatingPoint tr::rng::generate(FloatingPoint min, FloatingPoint max)
{
	TR_ASSERT(min < max, "RNG range minimum must be less than the maximum (Currenly: {} !< {})", min, max);

	return generate<FloatingPoint>() * (max - min) + min;
}

template <std::same_as<tr::angle>> tr::angle tr::rng::generate()
{
	return turns(generate<float>());
}

template <std::same_as<glm::vec2>> glm::vec2 tr::rng::generate(float magnitude)
{
	// Prefer this over generating an angle because trigonometric functions don't produce uniform results across platforms.
	const float sin2{generate<float>()};
	const float sin{std::sqrt(sin2) * generate_sign()};
	const float cos{std::sqrt(1 - sin2) * generate_sign()};
	return {magnitude * cos, magnitude * sin};
}

template <std::same_as<glm::vec2>> glm::vec2 tr::rng::generate(const tr::frect2& rect)
{
	return {generate(rect.tl.x, rect.tl.x + rect.size.x), generate(rect.tl.y, rect.tl.y + rect.size.y)};
}