add_executable(
	utility_test
	alignment.cpp
	atlas_packer.cpp
	atlas_entries.cpp
	benchmark.cpp
	binary_io.cpp
	circle.cpp
	color.cpp
	defer.cpp
	dynamic_ref_cast.cpp
	encryption.cpp
	enum.cpp
	handle.cpp
	hash_map.cpp
	localization_map.cpp
	math.cpp
	matrix.cpp
	mstream.cpp
	norm_cast.cpp
	opt_ref.cpp
	out_handle.cpp
	ranges.cpp
	rectangle_edges.cpp
	rectangle.cpp
	ref.cpp
	rng.cpp
	specialization_of.cpp
	static_vector.cpp
	stopwatch.cpp
	string_literal.cpp
	timer.cpp
	triangle.cpp
	type_name.cpp
	utf8.cpp
	variant.cpp
	zstring_view.cpp
)
target_link_libraries(
	utility_test
	tr::utility
	GTest::gtest_main
)

include(GoogleTest)
gtest_discover_tests(utility_test)